
    query outstanding($locale: I18NLocaleCode!) {
        products(locale: $locale, pagination: { limit: 4 }) {
            data {
            id
            attributes {
                title
                price
                slug
                feature {
                data {
                    attributes {
                    formats
                    }
                }
                }
            }
            }
        }
    }
