query user($id: ID) {
  usersPermissionsUser(id: $id) {
    data {
      attributes {
        email
        username
        company {
          data {
            attributes {
              name
              street
              city
              postal
              discount
            }
          }
        }
      }
    }
  }
}