export const MOSTAR_MODAL = 'MOSTAR_MODAL'
export const OCULTAR_MODAL = 'OCULTAR_MODAL'

/*REGISTRAR USUARIO*/
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const OBTENER_TOKEN = 'OBTENER_TOKEN';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const RESET_PASSWORD = 'RESET_PASSWORD';




/*PRODUCTOS*/
export const ULTIMOS_PRODUCTOS = 'ULTIMOS_PRODUCTOS';
export const PRODUCTO_BY_URL = 'PRODUCTO_BY_URL';
export const PRODUCTO_BY_ID = 'PRODUCTO_BY_ID';

//CART
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_ALL_PRODUCT = 'REMOVE_ALL_PRODUCT';
   