export const MOSTAR_MODAL = 'MOSTAR_MODAL'
export const OCULTAR_MODAL = 'OCULTAR_MODAL'

/*REGISTRAR USUARIO*/
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const OBTENER_TOKEN = 'OBTENER_TOKEN';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const RESET_PASSWORD = 'RESET_PASSWORD';




/*AUTH*/